name: Auto Commit

on:
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Auto commit from Codespace"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
